tree-sitter parse \
  Word/**/*.kind2 \
  Variadic/**/*.kind2 \
  Unit/**/*.kind2 \
  U240/**/*.kind2 \
  U120/**/*.kind2 \
  U60/**/*.kind2 \
  String/**/*.kind2 \
  Stream/**/*.kind2 \
  Sigma/**/*.kind2 \
  Show/**/*.kind2 \
  Quantifier/**/*.kind2 \
  Puzzle/**/*.kind2 \
  Parser/**/*.kind2 \
  Pair/**/*.kind2 \
  Not/**/*.kind2 \
  Nat/**/*.kind2 \
  Monad/**/*.kind2 \
  Maybe/**/*.kind2 \
  Map/**/*.kind2 \
  List/**/*.kind2 \
  Kindelia/**/*.kind2 \
  Kind/**/*.kind2 \
  KDL/**/*.kind2 \
  JSON/**/*.kind2 \
  Isomorphic/**/*.kind2 \
  IO/**/*.kind2 \
  IC/**/*.kind2 \
  HVM/**/*.kind2 \
  Function/**/*.kind2 \
  Format/**/*.kind2 \
  Fin/**/*.kind2 \
  F64/**/*.kind2 \
  Example/**/*.kind2 \
  Equivalence/**/*.kind2 \
  Equal/**/*.kind2 \
  Empty/**/*.kind2 \
  Either/**/*.kind2 \
  Dynamic/**/*.kind2 \
  Decidable/**/*.kind2 \
  Data/**/*.kind2 \
  Cmp/**/*.kind2 \
  Char/**/*.kind2 \
  Bool/**/*.kind2 \
  Bits/**/*.kind2 \
  Bit/**/*.kind2 \
  Apps/**/*.kind2 \
  App/**/*.kind2 \
  Algebra/**/*.kind2 \
  -q -t
